force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Used to store and manage individual job applications.  Captures essential job-related details such contact details, interview schedules, notes, and tasks</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <label>Application Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Job location (City, Remote, Hybrid, etc)</description>
    <inlineHelpText>Job location (City, Remote, Hybrid, etc)</inlineHelpText>
    <label>Location</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position_Title__c.field-meta.xml
<CustomField>
    <fullName>Position_Title__c</fullName>
    <label>Position/Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>Rate of salary in USD</description>
    <inlineHelpText>Rate of salary in USD</inlineHelpText>
    <label>Salary</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Source_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Id__c</fullName>
    <externalId>true</externalId>
    <label>Source Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/jobAppStatusUpdates_Test.cls
@IsTest

public with sharing class jobAppStatusUpdates_Test {
    @TestSetup

    static void createTestData(){
        // create with bulkification in mind, if needed
        List<Job_Application__c> jobAppList = new List<Job_Application__c>();
        for(Integer i = 0; i < 50; i++){
            jobAppList.add(new Job_Application__c(
                Name = 'Test ' + String.valueOf(i),
                Status__c = 'New',
                Position_Title__c = 'Test Dev ' + String.valueOf(i),
                Application_Date__c = System.today(),
                Salary__c = '115000',
                Location__c = 'Remote',
                Source_Id__c = 'SourceId_' + String.valueOf(i)
                )
            );
        }

        insert jobAppList;
    }

    @IsTest
    public static void jobAppStatusUpdates_afterUpdate_statusChange() {
        // Query and Edit Test Data
        List<Job_Application__c> testJobApps = [
            SELECT Id, Status__c 
            FROM Job_Application__c 
            ORDER BY CreatedDate ASC 
            LIMIT 7];

        testJobApps[0].Status__c = 'Saved';
        testJobApps[1].Status__c = 'Applying';
        testJobApps[2].Status__c = 'Applied';
        testJobApps[3].Status__c = 'Interviewing';
        testJobApps[4].Status__c = 'Negotiating';
        testJobApps[5].Status__c = 'Accepted';
        testJobApps[6].Status__c = 'Closed';

        // Test
        Test.startTest();
        update testJobApps;
        Test.stopTest();

        // Query count of tasks created based on Job App Id
        List<AggregateResult> taskCounts = [
            SELECT WhatId, COUNT(Id) taskCount
            FROM Task
            WHERE WhatId IN :testJobApps
            GROUP BY WhatId
        ];

        // Instantiate Map to associate Id and taskCounts
        Map<Id, Integer> taskCountMap = new Map<Id, Integer>();

        // Loop through Aggregate Results to build Map
        for(AggregateResult ar : taskCounts){
            taskCountMap.put((Id)ar.get('WhatId'), (Integer)ar.get('taskCount'));
        }

        // Assert correct number of tasks created based on Status
        Assert.areEqual(3, taskCountMap.get(testJobApps[0].Id), 'Saved status should have 3 tasks');
        Assert.areEqual(5, taskCountMap.get(testJobApps[1].Id), 'Applying status should have 5 tasks');
        Assert.areEqual(4, taskCountMap.get(testJobApps[2].Id), 'Applied status should have 4 tasks');
        Assert.areEqual(5, taskCountMap.get(testJobApps[3].Id), 'Interviewing status should have 5 tasks');
        Assert.areEqual(3, taskCountMap.get(testJobApps[4].Id), 'Negotiating status should have 3 tasks');
        Assert.areEqual(3, taskCountMap.get(testJobApps[5].Id), 'Accepted status should have 3 tasks');
        Assert.areEqual(2, taskCountMap.get(testJobApps[6].Id), 'Closed status should have 2 tasks');
        
    }

    @IsTest
    public static void jobAppStatusUpdates_afterUpdate_noStatusChange() {
        // Query and Edit Test Data
        List<Job_Application__c> testJobApps = [
            SELECT Id, Status__c FROM Job_Application__c LIMIT 5
        ];

        for(Job_Application__c jobApp : testJobApps) {
            jobApp.Salary__c = '120000 - 14000';
        }

        // Test
        Test.startTest();
        update testJobApps;
        Test.stopTest();

        // Query to find any created Tasks
        List<Task> createdTasks = [SELECT Id FROM Task WHERE WhatId IN :testJobApps];

        // Assert to confirm empty list
        Assert.areEqual(0, createdTasks.size(), 'No tasks should be created when status has not changed');
    }


}