force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Used to store and manage individual job applications.  Captures essential job-related details such contact details, interview schedules, notes, and tasks</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <label>Application Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Job location (City, Remote, Hybrid, etc)</description>
    <inlineHelpText>Job location (City, Remote, Hybrid, etc)</inlineHelpText>
    <label>Location</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position_Title__c.field-meta.xml
<CustomField>
    <fullName>Position_Title__c</fullName>
    <label>Position/Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>Rate of salary in USD</description>
    <inlineHelpText>Rate of salary in USD</inlineHelpText>
    <label>Salary</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Source_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Id__c</fullName>
    <externalId>true</externalId>
    <label>Source Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CleanUpStaleJobApplicationsQueueableTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CleanUpStaleJobApplicationsQueueableTest {

    @isTest
    static void testCleanUpStaleJobs() {
        // TO DO: implement unit test

        // Set and old date and a new date for follow up
        Date oldDate = Date.today().addDays(-31);
        Date newDate = Date.today().addDays(-10);

        // Create Job Applications with test data
        List<Job_Application__c> jobAppList = new List<Job_Application__c>{
            new Job_Application__c(
                Name = 'Old Test',
                Status__c = 'New',
                Position_Title__c = 'Test Dev',
                Application_Date__c = oldDate,
                Salary__c = '115000',
                Location__c = 'Remote',
                Notes__c = 'Old Application',
                Source_Id__c = 'TriggerSourceId',
                Follow_Up_Date__c = oldDate
                ),
            new Job_Application__c(
                Name = 'New Test',
                Status__c = 'New',
                Position_Title__c = 'Test Jr Dev',
                Application_Date__c = newDate,
                Salary__c = '115000',
                Location__c = 'Remote',
                Notes__c = 'New Application',
                Source_Id__c = 'TriggerSourceId',
                Follow_Up_Date__c = newDate
            ),
            new Job_Application__c(
                Name = 'Accepted Test',
                Status__c = 'New',
                Position_Title__c = 'Test Developer',
                Application_Date__c = oldDate,
                Salary__c = '115000',
                Location__c = 'Remote',
                Notes__c = 'Accepted Application',
                Source_Id__c = 'TriggerSourceId',
                Follow_Up_Date__c = oldDate
            )
          };

          // Insert list of test job applications
          insert jobAppList;

          // Set the status after insert to account for validation rule
          for (Job_Application__c jobApp : jobAppList) {
            if (jobApp.Name ==  'Old Test') {
                jobApp.Status__c = 'Closed';
            }

            if (jobApp.Name ==  'Accepted Test') {
                jobApp.Status__c = 'Accepted';
            }
          }
          
        Test.startTest();
        // Call the queueable class
        System.enqueueJob(new CleanUpStaleJobApplicationsQueueable());
        Test.stopTest();

        // Query for the results and place them in a map with the name as the key
        Map<String, Job_Application__c> results = new Map<String, Job_Application__c>();
            for (Job_Application__c jobMap : [
            SELECT Name, Status__c, Notes__c, Follow_Up_Date__c
            FROM Job_Application__c]) {
                results.put(jobMap.Name, jobMap);
            }
        
        // Old record should be closed
        System.assertEquals('Closed', results.get('Old Test').Status__c);
        System.assert(results.get('Old Test').Notes__c.contains('This job application has been closed by an automated process.'));
        
        // New record should not be closed
        System.assertNotEquals('Closed', results.get('New Test').Status__c);
          
        // Accepted should remain accepted
        System.assertEquals('Accepted', results.get('Accepted Test').Status__c);
    }
}